version: "3"
services:
  scrapy:
    build: ./hr
    env_file:
      - .env
    depends_on:
      - splash
  splash:
    image: scrapinghub/splash:latest
    ports:
      - 8050:8050
    expose:
      - 8050

